SELECT 
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
    (m.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM 
    ECOLI_DATA e
JOIN 
    (SELECT 
         YEAR(DIFFERENTIATION_DATE) AS YEAR,
         MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) m
  ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR, YEAR_DEV;
